# Generated by Django 4.2.1 on 2023-12-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='name_en',
        ),
    ]
