# Generated by Django 4.2.8 on 2023-12-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenda', '0003_country_alter_region_options_city_arenda_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город на английском'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна на английском'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион на английском'),
        ),
    ]
