# Generated by Django 4.2.8 on 2023-12-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenda', '0005_arenda_location_en_arenda_description_1_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenda',
            name='Location',
            field=models.CharField(default=1, max_length=200, verbose_name='Расположение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arenda',
            name='Location_en',
            field=models.CharField(default=1, max_length=100, verbose_name='Расположение на английском'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arenda',
            name='description',
            field=models.TextField(default=1, verbose_name='Информация об объекте'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arenda',
            name='description_en',
            field=models.TextField(default=1, verbose_name='Информация об объекте на английском'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arenda',
            name='name_en',
            field=models.CharField(default=1, max_length=100, verbose_name='Название на английском'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='Location',
            field=models.CharField(default=1, max_length=200, verbose_name='Расположение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='Location_en',
            field=models.CharField(default=1, max_length=200, verbose_name='Расположение на английском'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='description',
            field=models.TextField(default=1, verbose_name='Информация об объекте'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='description_en',
            field=models.TextField(default=1, verbose_name='Информация об объекте на английском'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='name_en',
            field=models.CharField(default=1, max_length=100, verbose_name='Название на английском'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yacht',
            name='Location',
            field=models.CharField(default=1, max_length=200, verbose_name='Расположение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yacht',
            name='Location_en',
            field=models.CharField(default=1, max_length=200, verbose_name='Расположение на английском'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yacht',
            name='description',
            field=models.TextField(default=1, verbose_name='Информация об объекте'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yacht',
            name='description_en',
            field=models.TextField(default=1, verbose_name='Информация об объекте на английском'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yacht',
            name='name_en',
            field=models.CharField(default=1, max_length=100, verbose_name='Название на английском'),
            preserve_default=False,
        ),
    ]
