# Generated by Django 4.2.1 on 2023-12-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenda', '0006_alter_arenda_location_alter_arenda_location_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Популярные направления ?'),
        ),
        migrations.AddField(
            model_name='country',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Популярные направления ?'),
        ),
        migrations.AddField(
            model_name='region',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='Популярные направления ?'),
        ),
    ]
