# Generated by Django 4.2.1 on 2023-12-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenda', '0007_city_popular_country_popular_region_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenda',
            name='property_type',
            field=models.CharField(choices=[('vila', 'Villa'), ('shale', 'Chalet'), ('apartamenti', 'Apartment'), ('yaxta', 'Yacht')], max_length=15, verbose_name='тип жилья'),
        ),
        migrations.AlterField(
            model_name='arenda',
            name='property_type_2',
            field=models.CharField(choices=[('rent', 'Rent'), ('buy', 'Buy')], default='rent', max_length=10, verbose_name='Аренда или Купить?'),
        ),
    ]
