# Generated by Django 4.2.1 on 2023-12-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenda', '0009_alter_sale_property_type_alter_sale_property_type_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Картина'),
        ),
        migrations.AddField(
            model_name='country',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Картина'),
        ),
        migrations.AddField(
            model_name='region',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Картина'),
        ),
    ]
