# Generated by Django 4.2.1 on 2023-12-28 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arenda', '0011_imgmain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgmain',
            name='name',
        ),
    ]
